### ISSUE TITLE
Grimoire folder is not being generated

### ISSUE THREAD

**Issue by joaoespanhol** [CrucibleMC/Grimoire#18]
I have installed grimoire on the mods folder, but there is no grimoire folder for me to install the mixins

version 1.7.1.0

**Comment by drori200** [comment]
You need to add the mixins to the mods folder afaik

**Comment by Aizistral** [comment]
Don't see any bugs here, @evernife. I thought we all agreed we don't need to make a legacy support for feature that was already legacy in legacy version of Grimoire

**Comment by evernife** [comment]
Do not generate the folder `grimoire` when legacy is enabled is the bug.

But, besides that, I am still on grimoire v1

I am reading thought all modifications thought the versions, after that i will do some changes and than maybe i will upgrade all my mixins to the new version.

**Comment by joaoespanhol** [comment]
> Don't see any bugs here, @evernife. I thought we all agreed we don't need to make a legacy support for feature that was already legacy in legacy version of Grimoire

in version 1.7.1.0 it is not generating the grimoire folder to put mixis-mods

**Comment by Aizistral** [comment]
That folder was removed in v2 guys. You just use mods folder for the purpose it had

**Comment by spannerman79** [comment]
... and why https://github.com/CrucibleMC/Grimoire/wiki should be used.

Shouldn't have to crawl through commit messages or know the codebase offhand to know.

**Comment by Aizistral** [comment]
> ... and why https://github.com/CrucibleMC/Grimoire/wiki should be used/updated.
> 
> Shouldn't have to crawl through commit messages or know the codebase offhand to know.

Juan once said he'll be working on wiki. Some 4 months ago

**Comment by evernife** [comment]
> That folder was removed in v2 guys. You just use mods folder for the purpose it had

So, if there are 20 mixins modules (each one in each jar) you just throw all of them in the mods folder?

![image](https://user-images.githubusercontent.com/11357801/140578170-ed9fdbd2-3c70-4798-b4d6-98be6e360e32.png)

**Comment by Aizistral** [comment]
> So, if there are 20 mixins modules (each one in each jar) you just throw all of them in the mods folder?

I dunno, probably? Honestly that's why I would've preffered there to be a single mod with config to disable or enable individual modules

**Comment by evernife** [comment]
Sure, to be honest i don't have time to nor the wish to discuss something that is so meaningless.

`"Generate a folder called grimoire for just a better organization"
`

After juan finishes his coremod transcription i may apply the remaining mixins. His coremod will be into a single jar so might not even need the folder anymore.
 
After that we will even be able to just drop support for legacy mixins.
