### ISSUE TITLE
MixinForge - MixinTileEntity

### ISSUE THREAD

**Issue by LucasTSu** [CrucibleMC/Grimoire#3]
Olá, estou usando o Grimoire e tive alguns problemas, mas não consegui resolver sozinho, até agora só tive problema na Digital Miner e no Mana Spreader, quando o bloco é colocado no chão o servidor "crasha" e quando a _chunk_ é carregada o servidor crasha, falei com o Brunoxkk0 e ele pediu para que eu criasse uma _issue_ aqui no GitHub, mas a parte de Issues está desabilitada no Grimoire-Mixins
por isso estou criando aqui.
Aqui está o crash report: `https://pastebin.com/GaGUWLj6` do servidor.
Eu testei apenas com o Mixins do Forge e o Botania apenas no servidor.
Meu discord:`carmello#0760`

**Comment by evernife** [comment]
Ta usando Thermos ou Crucible?

**Comment by LucasTSu** [comment]
Thermos

**Comment by LucasTSu** [comment]
o Bruno falou que não precisa do Crucible para funcionar

**Comment by evernife** [comment]
De fato não precisa, mas testa para a gente ver :D
https://github.com/CrucibleMC/Crucible/releases

--- 
O erro que está dando é de abstract method.
Me manda o log completo por favor :D

**Comment by LucasTSu** [comment]
https://paste.ee/p/hgFCO
Não consegui mandar pelo Pastebin ou Hastebin.
Agora vou testar com o Crucible.

**Comment by LucasTSu** [comment]
Crucible
Log: https://paste.ee/p/P3c1X
Crash-Report: https://paste.ee/p/vJw1K

**Comment by evernife** [comment]
Testa com esse forgemixin:

[forgemixin.zip](https://github.com/CrucibleMC/Grimoire/files/4079541/forgemixin.zip)

E me manda o log denovo quando testar!

**Comment by LucasTSu** [comment]
Vou testar no Crucible.

**Comment by LucasTSu** [comment]
Log: https://paste.ee/p/23y5s 
Crash: https://paste.ee/p/YVssQ

**Comment by evernife** [comment]
O mixin forge está com problemas, vou tentar corrigir depois.
Por hora, nao use mixins que precisam dele.

**Comment by LucasTSu** [comment]
Tudo bem, obrigado pelo suporte.

**Comment by evernife** [comment]
@LucasTSu Testa lá agora meu bom :D

https://github.com/CrucibleMC/Grimoire-Mixins/releases/tag/v1.0.1b

**Comment by LucasTSu** [comment]
Bom, está funcionando não sei entendi o porque estava dando alguns _crashes_, mas está funcionando, obrigado por tudo.
Uma sugestão, criar um arquivo comprimido com todos os Mixins, porque eu uso todos(Preciso de todos, kk) em meu servidor e fica meio chato para baixar um por um.
Att, Lucas

**Comment by evernife** [comment]
Infelizmente isso iria causar alguns problemas como pessoas baixando tudo sem saber, infelizmente teremos que manter todos eles separados T.T
